pub mod usb_cmd;
pub mod usb_sts;
pub mod page_size;
pub mod device_notification_control;
pub mod command_ring_control;
pub mod dcbaap;
pub mod configure;
pub mod port_status_and_control;
pub mod operational_registers;
