#[unstable]
#build-std = ["core", "compiler_builtins", "alloc"]
#build-std-features = ["compiler-builtins-mem"]
#
#[build]
#target = "x86_64-blog_os.json"
#rustflags = ["-C", "link-args=-lc"]

[target.'cfg(target_os = "none")']
runner = "cargo run --package disk_image --bin runner --quiet"

[alias]
#xbuild = "xbuild --target x86_64-blog_os.json -Zbuild-std=core,alloc,compiler_builtins  -Zbuild-std-features=compiler-builtins-mem"
r = "run --target x86_64-blog_os.json -Zbuild-std=core,alloc,compiler_builtins  -Zbuild-std-features=compiler-builtins-mem"
t = "test --target x86_64-blog_os.json -Zbuild-std=core,alloc,compiler_builtins  -Zbuild-std-features=compiler-builtins-mem"
bootimage = "run --package disk_image --bin disk_image --quiet"